### ISSUE TITLE
Captions data

### ISSUE THREAD

**Issue by humanely** [zyinghua/uncond-image-generation-ldm#1]
Can you please explain if how are you loading the captions data with images?

**Comment by zyinghua** [comment]
Hi!
This codebase is solely for unconditional image generation, so it doesn't supported text conditioning, if you are looking for text-to-image gen task or similar ones I'd suggest having a look at the [official diffusers text-to-image sub-repo](https://github.com/huggingface/diffusers/tree/main/examples/text_to_image), hope this helps! :)

**Comment by zyinghua** [comment]
> Can you please explain if how are you loading the captions data with images?

Hi!
This codebase is solely for unconditional image generation, so it doesn't supported text conditioning, if you are looking for text-to-image gen task or similar ones I'd suggest having a look at the [official diffusers text-to-image sub-repo](https://github.com/huggingface/diffusers/tree/main/examples/text_to_image), hope this helps! :)
