### ISSUE TITLE
May I ask for the result?

### ISSUE THREAD

**Issue by nessessence** [zyinghua/uncond-image-generation-ldm#2]
Hi, I appreciate that you release the code here.
I wonder if you have test the code in training process?

**Comment by zyinghua** [comment]
Hi nessessence!
Thanks for your interest! Yea I have ran the code before, but I stopped at around 100 epochs for some reasons, was training on the flowers dataset, the images looked reasonable for 100 epochs tho. Are you having problems with the code in anyway? Btw if I recall correctly accelerate config as well as the environment could affect the code run
