### ISSUE TITLE
How to make inference and inference error.

### ISSUE THREAD

**Issue by hnyll** [zyinghua/uncond-image-generation-ldm#3]
i trained a model by following the instructions provided but when i try to run the inference code i get an error saying that there are keys missing

![화면 캡처 2024-06-12 142110](https://github.com/zyinghua/uncond-image-generation-ldm/assets/65143869/8f8267bd-0ebd-464a-9010-842eeca1f022)

> ValueError: Cannot load <class 'diffusers.models.unets.unet_2d.UNet2DModel'> from /home/david/testing/uncond-image-generation-ldm/output/vae because the following keys are missing: 
 down_blocks.2.resnets.0.norm1.bias, up_blocks.2.resnets.2.time_emb_proj.bias, up_blocks.2.resnets.2.norm1.bias, down_blocks.1.resnets.1.norm2.weight, mid_block.resnets.0.time_emb_proj.weight, down_blocks.2.resnets.0.norm1.weight, up_blocks.1.resnets.2.norm2.weight, up_blocks.1.resnets.1.conv1.bias, down_blocks.2.resnets.1.conv1.weight, down_blocks.1.resnets.1.conv1.weight, mid_block.attentions.0.to_q.weight, down_blocks.0.resnets.0.norm2.bias, up_blocks.2.resnets.0.norm2.bias, up_blocks.0.resnets.1.norm2.bias, up_blocks.0.resnets.2.conv1.weight, up_blocks.0.resnets.0.norm1.bias, conv_out.weight, up_blocks.0.resnets.0.time_emb_proj.bias, down_blocks.0.downsamplers.0.conv.weight, mid_block.attentions.0.to_k.weight, mid_block.resnets.1.norm1.bias, conv_out.bias, up_blocks.1.resnets.2.conv1.bias, up_blocks.0.resnets.0.time_emb_proj.weight, down_blocks.2.resnets.1.norm2.weight, up_blocks.1.upsamplers.0.conv.bias, up_blocks.2.resnets.1.time_emb_proj.weight, mid_block.attentions.0.to_v.weight, up_blocks.2.resnets.1.conv2.weight, down_blocks.1.resnets.1.conv2.weight, up_blocks.1.resnets.2.conv2.bias, mid_block.attentions.0.to_v.bias, down_blocks.1.resnets.0.conv_shortcut.bias, up_blocks.0.resnets.1.norm2.weight, up_blocks.0.resnets.2.norm1.weight, down_blocks.1.downsamplers.0.conv.weight, up_blocks.1.resnets.0.norm2.weight, up_blocks.1.resnets.0.conv2.weight, mid_block.resnets.0.norm1.weight, up_blocks.0.resnets.1.conv2.bias, down_blocks.1.resnets.0.norm1.weight, down_blocks.0.resnets.0.norm2.weight, down_blocks.1.resnets.0.norm2.weight, mid_block.resnets.0.conv2.bias, up_blocks.0.resnets.0.norm2.weight, up_blocks.1.resnets.2.norm2.bias, mid_block.resnets.0.conv2.weight, down_blocks.0.resnets.1.norm2.bias, down_blocks.2.resnets.0.conv1.bias, up_blocks.0.resnets.0.conv2.bias, up_blocks.2.resnets.1.norm2.weight, down_blocks.0.downsamplers.0.conv.bias, up_blocks.2.resnets.1.norm1.bias, time_embedding.linear_2.bias, up_blocks.1.resnets.1.conv2.weight, up_blocks.1.resnets.2.norm1.weight, down_blocks.0.resnets.0.conv2.bias, up_blocks.2.resnets.2.norm1.weight, conv_norm_out.weight, up_blocks.2.resnets.2.norm2.weight, down_blocks.0.resnets.1.conv2.weight, mid_block.attentions.0.group_norm.weight, up_blocks.0.resnets.1.conv1.bias, up_blocks.2.resnets.0.time_emb_proj.bias, up_blocks.1.upsamplers.0.conv.weight, mid_block.resnets.0.norm2.bias, up_blocks.1.resnets.0.conv_shortcut.bias, up_blocks.0.resnets.2.norm2.bias, up_blocks.0.resnets.2.conv1.bias, up_blocks.1.resnets.1.norm2.bias, mid_block.resnets.1.norm2.weight, up_blocks.1.resnets.0.norm1.weight, up_blocks.1.resnets.1.time_emb_proj.weight, down_blocks.1.resnets.0.conv1.bias, down_blocks.2.resnets.0.conv2.weight, up_blocks.0.resnets.2.time_emb_proj.weight, up_blocks.2.resnets.1.norm1.weight, up_blocks.1.resnets.1.conv1.weight, down_blocks.2.resnets.0.conv2.bias, up_blocks.0.resnets.0.conv_shortcut.weight, up_blocks.0.resnets.2.norm1.bias, up_blocks.0.resnets.2.conv2.bias, up_blocks.2.resnets.0.norm1.bias, down_blocks.0.resnets.0.conv1.weight, conv_in.weight, down_blocks.0.resnets.0.norm1.bias, mid_block.resnets.1.norm1.weight, down_blocks.1.resnets.1.conv1.bias, down_blocks.2.resnets.1.norm2.bias, up_blocks.1.resnets.1.norm1.weight, mid_block.resnets.0.norm2.weight, time_embedding.linear_2.weight, up_blocks.2.resnets.0.conv1.bias, down_blocks.2.resnets.1.conv1.bias, mid_block.attentions.0.to_out.0.weight, up_blocks.2.resnets.0.norm2.weight, up_blocks.2.resnets.1.conv1.bias, down_blocks.0.resnets.1.norm1.weight, up_blocks.2.resnets.2.time_emb_proj.weight, time_embedding.linear_1.weight, up_blocks.2.resnets.1.conv1.weight, down_blocks.1.downsamplers.0.conv.bias, up_blocks.0.resnets.1.time_emb_proj.weight, down_blocks.0.resnets.0.norm1.weight, down_blocks.1.resnets.0.norm1.bias, mid_block.resnets.0.conv1.weight, up_blocks.2.resnets.1.conv2.bias, down_blocks.2.resnets.1.conv2.bias, up_blocks.0.resnets.0.conv_shortcut.bias, up_blocks.1.resnets.1.time_emb_proj.bias, up_blocks.1.resnets.2.time_emb_proj.weight, mid_block.resnets.1.conv2.weight, up_blocks.0.upsamplers.0.conv.weight, down_blocks.0.resnets.1.conv1.bias, down_blocks.1.resnets.1.norm1.bias, up_blocks.0.resnets.0.conv1.bias, mid_block.resnets.1.time_emb_proj.weight, down_blocks.1.resnets.0.conv2.bias, up_blocks.0.resnets.1.norm1.weight, up_blocks.2.resnets.0.time_emb_proj.weight, up_blocks.2.resnets.2.conv2.weight, mid_block.resnets.1.conv1.bias, time_embedding.linear_1.bias, up_blocks.1.resnets.0.conv_shortcut.weight, mid_block.attentions.0.to_q.bias, up_blocks.1.resnets.0.conv1.bias, down_blocks.1.resnets.1.conv2.bias, down_blocks.1.resnets.0.conv2.weight, down_blocks.0.resnets.1.norm2.weight, up_blocks.1.resnets.2.time_emb_proj.bias, up_blocks.0.resnets.2.time_emb_proj.bias, up_blocks.1.resnets.1.conv2.bias, up_blocks.0.resnets.0.conv1.weight, mid_block.attentions.0.to_k.bias, down_blocks.0.resnets.0.conv1.bias, up_blocks.2.resnets.0.conv1.weight, up_blocks.0.resnets.0.norm2.bias, mid_block.resnets.1.conv1.weight, mid_block.resnets.1.time_emb_proj.bias, down_blocks.0.resnets.1.norm1.bias, mid_block.resnets.1.conv2.bias, up_blocks.0.upsamplers.0.conv.bias, up_blocks.2.resnets.2.conv2.bias, up_blocks.0.resnets.1.norm1.bias, down_blocks.1.resnets.1.norm1.weight, down_blocks.2.resnets.0.conv_shortcut.bias, down_blocks.1.resnets.0.conv_shortcut.weight, down_blocks.2.resnets.0.norm2.bias, up_blocks.0.resnets.1.conv1.weight, down_blocks.0.resnets.1.conv1.weight, up_blocks.1.resnets.2.conv1.weight, up_blocks.0.resnets.2.norm2.weight, up_blocks.1.resnets.2.norm1.bias, mid_block.attentions.0.group_norm.bias, up_blocks.2.resnets.2.norm2.bias, down_blocks.2.resnets.1.norm1.weight, mid_block.resnets.0.time_emb_proj.bias, mid_block.attentions.0.to_out.0.bias, up_blocks.0.resnets.0.norm1.weight, up_blocks.0.resnets.1.time_emb_proj.bias, up_blocks.0.resnets.0.conv2.weight, down_blocks.1.resnets.0.norm2.bias, conv_norm_out.bias, up_blocks.1.resnets.0.norm2.bias, down_blocks.1.resnets.1.norm2.bias, conv_in.bias, up_blocks.0.resnets.1.conv2.weight, mid_block.resnets.0.conv1.bias, down_blocks.2.resnets.0.conv1.weight, up_blocks.2.resnets.1.norm2.bias, down_blocks.2.resnets.0.norm2.weight, down_blocks.1.resnets.0.conv1.weight, down_blocks.2.resnets.1.conv2.weight, up_blocks.2.resnets.0.conv2.weight, up_blocks.1.resnets.0.conv2.bias, down_blocks.2.resnets.1.norm1.bias, up_blocks.1.resnets.0.conv1.weight, up_blocks.0.resnets.2.conv2.weight, up_blocks.1.resnets.0.time_emb_proj.weight, up_blocks.2.resnets.2.conv1.bias, up_blocks.1.resnets.1.norm1.bias, down_blocks.2.resnets.0.conv_shortcut.weight, up_blocks.2.resnets.0.conv2.bias, up_blocks.2.resnets.0.norm1.weight, up_blocks.1.resnets.0.norm1.bias, up_blocks.1.resnets.1.norm2.weight, up_blocks.2.resnets.1.time_emb_proj.bias, down_blocks.0.resnets.0.conv2.weight, down_blocks.0.resnets.1.conv2.bias, mid_block.resnets.1.norm2.bias, mid_block.resnets.0.norm1.bias, up_blocks.1.resnets.0.time_emb_proj.bias, up_blocks.1.resnets.2.conv2.weight, up_blocks.2.resnets.2.conv1.weight. 
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.

**Comment by zyinghua** [comment]
Hi!
Thanks for your issue. There has been some time since the last time I touched this project, however, I'd suggest first making sure the path matches (as specified in model_id in inference.py), since it seems like you are trying to load a UNet model from ".../output/vae" path, the path if I recall correct might be the path one-level up of your current one, or the one that contains unet, logs, scheduler folders, etc. Anyway please double check the path as the error suggests it is more likely to do with mismatching ckpt file; otherwise huggingface [diffusers](https://github.com/huggingface/diffusers) repo may be a helpful resource as this repo inherits theirs, if problem persists feel free to follow up, I can try to have a look when I have time!

**Comment by hnyll** [comment]
thanks for the quick response! i just needed to include the config.json and scheduler_config.json to fix the error but now i get a different error. did you happen to get this error? 
![화면 캡처 2024-06-12 144625](https://github.com/zyinghua/uncond-image-generation-ldm/assets/65143869/2a574b60-35ff-493a-b4c5-a2c15dd6d96f)

i will take a look at the huggingface diffusers repo

**Comment by zyinghua** [comment]
I think the time I ran the inference code with my trained model using the scripts was error-free, so I didn't receive this error, can you double check if the ckpt files are loaded correctly for unet and vae respectively? I'd suggest loading from the path containing the unet, scheduler, vae folders, etc. as given by training if I recall correctly, like the hierachy in [here](https://huggingface.co/CompVis/ldm-celebahq-256/tree/main). Feel free to follow up if problem persists!

**Comment by hnyll** [comment]
aha ok yea that works. i just had to include the filepath from one hierarchy above like you said
